import type { Config } from 'tailwindcss'

/**
 * Tema do MIZ Loja: SÓ os tokens de src/styles/tokens.css.
 * As paletas, tamanhos e raios padrão do Tailwind foram substituídos,
 * então uma classe fora do design system (ex.: bg-blue-500) não existe.
 */
const v = (nome: string) => `var(--${nome})`

const espacos = {
  0: '0',
  px: '1px',
  1: v('space-1'),
  2: v('space-2'),
  3: v('space-3'),
  4: v('space-4'),
  5: v('space-5'),
  6: v('space-6'),
  8: v('space-8'),
  10: v('space-10'),
  14: v('space-14'),
  18: v('space-18'),
  gutter: v('gutter'),
  // medidas de componentes
  toque: v('size-touch'),
  'btn-lg': v('size-btn-lg'),
  'btn-md': v('size-btn-md'),
  'btn-sm': v('size-btn-sm'),
  campo: v('size-field'),
  'campo-valor': v('size-field-money'),
  'campo-hex': v('size-field-hex'),
  chip: v('size-chip'),
  'chip-filtro': v('size-chip-filter'),
  escolha: v('size-choice'),
  peca: v('size-peca'),
  topbar: v('size-topbar'),
  rodape: v('size-bottomnav'),
  pasta: v('size-pasta'),
  sidebar: v('size-sidebar'),
  'sidebar-item': v('size-sidebar-item'),
  segmentado: v('size-segmented'),
  selo: v('size-badge'),
  barra: v('size-progress'),
  stepper: v('size-stepper-w'),
  passo: v('size-step'),
  'passo-h': v('size-step-h'),
  'alca-w': v('size-handle-w'),
  'alca-h': v('size-handle-h'),
  'icone-sm': v('size-icon-sm'),
  icone: v('size-icon'),
  'icone-nav': v('size-icon-nav'),
  'icone-vazio': v('size-icon-empty'),
  'icone-sucesso': v('size-icon-success'),
  'bolinha-lg': v('size-dot-lg'),
  bolinha: v('size-dot'),
  'bolinha-sm': v('size-dot-sm'),
  logo: v('size-logo'),
  faixa: v('size-banner'),
  grafico: v('size-chart'),
  'grafico-rotulo': v('size-chart-label'),
  'barra-h': v('size-bar'),
}

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    screens: { md: '768px', lg: '1200px' },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      surface: v('color-surface'),
      background: v('color-background'),
      'background-muted': v('color-background-muted'),
      'border-subtle': v('color-border-subtle'),
      border: v('color-border'),
      'border-strong': v('color-border-strong'),
      'icon-muted': v('color-icon-muted'),
      'text-placeholder': v('color-text-placeholder'),
      'text-tertiary': v('color-text-tertiary'),
      'text-secondary': v('color-text-secondary'),
      'primary-hover': v('color-primary-hover'),
      'surface-inverse': v('color-surface-inverse'),
      primary: v('color-primary'),
      'text-primary': v('color-text-primary'),
      pressed: v('color-pressed'),
      'on-primary': v('color-on-primary'),
      scrim: v('color-scrim'),
      success: v('color-success'),
      warning: v('color-warning'),
      danger: v('color-danger'),
      'success-soft': v('color-success-soft'),
      'warning-soft': v('color-warning-soft'),
      'danger-soft': v('color-danger-soft'),
    },
    fontFamily: { sans: v('font-family') },
    letterSpacing: { normal: '0', overline: v('tracking-overline'), display: v('tracking-display'), logo: v('tracking-logo') },
    fontWeight: { regular: v('font-regular'), semibold: v('font-semibold'), bold: v('font-bold') },
    fontSize: {
      display: [v('fs-display'), { lineHeight: v('lh-display'), letterSpacing: v('tracking-display'), fontWeight: v('font-bold') }],
      h1: [v('fs-h1'), { lineHeight: v('lh-h1'), fontWeight: v('font-bold') }],
      h2: [v('fs-h2'), { lineHeight: v('lh-h2'), fontWeight: v('font-bold') }],
      h3: [v('fs-h3'), { lineHeight: v('lh-h3'), fontWeight: v('font-bold') }],
      body: [v('fs-body'), { lineHeight: v('lh-body'), fontWeight: v('font-regular') }],
      'body-sm': [v('fs-body-sm'), { lineHeight: v('lh-body-sm'), fontWeight: v('font-regular') }],
      label: [v('fs-label'), { lineHeight: v('lh-label'), fontWeight: v('font-semibold') }],
      overline: [v('fs-overline'), { lineHeight: v('lh-overline'), letterSpacing: v('tracking-overline'), fontWeight: v('font-semibold') }],
      caption: [v('fs-caption'), { lineHeight: v('lh-caption'), fontWeight: v('font-regular') }],
      input: [v('fs-input'), { lineHeight: v('lh-body') }],
      pasta: [v('fs-pasta'), { lineHeight: v('fs-pasta'), letterSpacing: v('tracking-display'), fontWeight: v('font-bold') }],
    },
    spacing: espacos,
    borderRadius: {
      none: '0',
      xs: v('radius-xs'),
      sm: v('radius-sm'),
      md: v('radius-md'),
      lg: v('radius-lg'),
      full: v('radius-full'),
    },
    borderWidth: { DEFAULT: '1px', 0: '0', 1: '1px', '1.5': '1.5px', 2: '2px' },
    boxShadow: {
      none: 'none',
      float: v('shadow-float'),
      fab: v('shadow-fab'),
      top: v('shadow-top'),
    },
    ringWidth: { 0: '0', 2: '2px' },
    ringOffsetWidth: { 0: '0', 2: '2px' },
    transitionDuration: { fast: v('duration-fast'), base: v('duration-base'), slow: v('duration-slow') },
    transitionTimingFunction: { DEFAULT: v('ease-base'), base: v('ease-base'), out: 'ease-out' },
    extend: {
      maxWidth: {
        form: v('size-form-max'),
        conteudo: v('size-content-max'),
        folha: v('size-sheet-max'),
      },
      maxHeight: { folha: v('size-sheet-max-h') },
      minHeight: { tela: '100dvh' },
      height: { tela: '100dvh' },
      keyframes: {
        pulsar: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        ponto: { '0%, 80%, 100%': { opacity: '0.2' }, '40%': { opacity: '1' } },
        subir: { from: { transform: 'translateY(100%)' }, to: { transform: 'translateY(0)' } },
        aparecer: { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      animation: {
        pulsar: 'pulsar 1.4s ease-in-out infinite',
        ponto: 'ponto 1.2s ease-in-out infinite',
        subir: 'subir var(--duration-base) var(--ease-base)',
        aparecer: 'aparecer var(--duration-base) var(--ease-base)',
      },
      scale: { 98: '0.98' },
    },
  },
  plugins: [],
}

export default config
